[package]
name = "obsidian-rantlang-plugin"
version = "0.2.3"
authors = ["lanice"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
getrandom = { version="*", features = ["js"] }
rant = "4.0.0-alpha.31"
