[package]
name = "obsidian-rantlang-plugin"
version = "0.2.1"
authors = ["lanice"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
getrandom = { version="*", features = ["js"] }
rant = { git = "https://github.com/lanice/rant" }
